### ISSUE TITLE
simpler readdir

### ISSUE THREAD

**Issue by pauljohnleonard** [fintechneo/angular-git-filebrowser#3]
The readdir() seems to do a lot more than simply return a list of files in a folder.

Here is a simple version that does the minimum required.

```
   /*
     * simple readdir list the files names in the path
     */
    readdirPJL(path?: string): Observable<string[]> {
        if (path === undefined) {
            path = '.';
        }
        return this.callWorker2((params) =>
            FS.readdir(params.path), { path: path });
    }
```

**Comment by petersalomonsen** [comment]
Simple readdir is supported by specifying a path, where only a list of string will be returned, and no listeners will be notified. We want to keep the current readdir with no params as it notifies the subjects for listeners so that the filebrowser user interface can be updated when there are incoming file changes. See updated docs for the readdir method in this PR: https://github.com/fintechneo/angular-git-filebrowser/pull/13/files
